Repository TiagoFar78/PrisonEscape, pull requests merged in 2024-04, with the labels that each got.

#98 Chests
  src/main/java/net/tiagofar78/prisonescape/Events.java
  src/main/java/net/tiagofar78/prisonescape/bukkit/BukkitInventory.java
  src/main/java/net/tiagofar78/prisonescape/bukkit/BukkitMenu.java
  src/main/java/net/tiagofar78/prisonescape/game/MenuType.java
  src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java
  src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapePlayer.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/Chest.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/ClickReturnAction.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/Clickable.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/PrisonBuilding.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/PrisonEscapeLocation.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/Vault.java
  src/main/java/net/tiagofar78/prisonescape/managers/ConfigManager.java
  src/main/java/net/tiagofar78/prisonescape/managers/MessageLanguageManager.java
  src/main/resources/config.yml
  src/main/resources/languages/english.yml
Labels: enhancement

#112 Building section on READ.ME
  README.md
Labels: documentation

#113 Player Inventory Clicks
  src/main/java/net/tiagofar78/prisonescape/Events.java
  src/main/java/net/tiagofar78/prisonescape/bukkit/BukkitMenu.java
  src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/Chest.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/Clickable.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/PrisonBuilding.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/Vault.java
Labels: enhancement

#115 Created variable for player
  src/main/java/net/tiagofar78/prisonescape/Events.java
Labels: enhancement

#121 Secret Passages Movement
  src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/PrisonBuilding.java
Labels: enhancement

#123 Fix mob spawning in prison
  src/main/java/net/tiagofar78/prisonescape/Events.java
Labels: bug fix

#129 Chests Considering Location
  src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/Chest.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/PrisonBuilding.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/PrisonEscapeLocation.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/regions/ComplexRegion.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/regions/Locatable.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/regions/Region.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/regions/SquaredRegion.java
  src/main/java/net/tiagofar78/prisonescape/managers/ConfigManager.java
  src/main/resources/config.yml
Labels: enhancement

#134 Rework items
  src/main/java/net/tiagofar78/prisonescape/Events.java
  src/main/java/net/tiagofar78/prisonescape/PrisonEscape.java
  src/main/java/net/tiagofar78/prisonescape/bukkit/BukkitEffectGiver.java
  src/main/java/net/tiagofar78/prisonescape/bukkit/BukkitItems.java
  src/main/java/net/tiagofar78/prisonescape/bukkit/BukkitMenu.java
  src/main/java/net/tiagofar78/prisonescape/dataobjects/ItemProbability.java
  src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java
  src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeItem.java
  src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapePlayer.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/Chest.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/Clickable.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/Vault.java
  src/main/java/net/tiagofar78/prisonescape/items/AntenaItem.java
  src/main/java/net/tiagofar78/prisonescape/items/BatteryItem.java
  src/main/java/net/tiagofar78/prisonescape/items/BoltsItem.java
  src/main/java/net/tiagofar78/prisonescape/items/CircuitBoardItem.java
  src/main/java/net/tiagofar78/prisonescape/items/CopperItem.java
  src/main/java/net/tiagofar78/prisonescape/items/DuctTapeItem.java
  src/main/java/net/tiagofar78/prisonescape/items/EnergyDrinkItem.java
  src/main/java/net/tiagofar78/prisonescape/items/FunctionalItem.java
  src/main/java/net/tiagofar78/prisonescape/items/GoldBarItem.java
  src/main/java/net/tiagofar78/prisonescape/items/HandcuffsItem.java
  src/main/java/net/tiagofar78/prisonescape/items/Item.java
  src/main/java/net/tiagofar78/prisonescape/items/ItemFactory.java
  src/main/java/net/tiagofar78/prisonescape/items/MatchesItem.java
  src/main/java/net/tiagofar78/prisonescape/items/MetalPlateItem.java
  src/main/java/net/tiagofar78/prisonescape/items/NotePartItem.java
  src/main/java/net/tiagofar78/prisonescape/items/NullItem.java
  src/main/java/net/tiagofar78/prisonescape/items/OilItem.java
  src/main/java/net/tiagofar78/prisonescape/items/PlasticPlateItem.java
  src/main/java/net/tiagofar78/prisonescape/items/SearchItem.java
  src/main/java/net/tiagofar78/prisonescape/items/SelectNoneTeamItem.java
  src/main/java/net/tiagofar78/prisonescape/items/SelectPoliceTeamItem.java
  src/main/java/net/tiagofar78/prisonescape/items/SelectPrisionerTeamItem.java
  src/main/java/net/tiagofar78/prisonescape/items/StickItem.java
  src/main/java/net/tiagofar78/prisonescape/kits/TeamSelectorKit.java
  src/main/java/net/tiagofar78/prisonescape/managers/ConfigManager.java
  src/main/java/net/tiagofar78/prisonescape/managers/MessageLanguageManager.java
  src/main/resources/config.yml
  src/main/resources/languages/english.yml
Labels: enhancement

#147 Tool Items
  src/main/java/net/tiagofar78/prisonescape/items/Item.java
  src/main/java/net/tiagofar78/prisonescape/items/ItemFactory.java
  src/main/java/net/tiagofar78/prisonescape/items/MetalShovelItem.java
  src/main/java/net/tiagofar78/prisonescape/items/MetalSpoonItem.java
  src/main/java/net/tiagofar78/prisonescape/items/PlasticShovelItem.java
  src/main/java/net/tiagofar78/prisonescape/items/PlasticSpoonItem.java
  src/main/java/net/tiagofar78/prisonescape/items/ToolItem.java
  src/main/java/net/tiagofar78/prisonescape/items/WireCutterItem.java
  src/main/java/net/tiagofar78/prisonescape/items/WrenchItem.java
  src/main/resources/languages/english.yml
Labels: enhancement

#150 Remove minecraft attributes from tools lore
  src/main/java/net/tiagofar78/prisonescape/bukkit/BukkitItems.java
  src/main/java/net/tiagofar78/prisonescape/items/MetalShovelItem.java
  src/main/java/net/tiagofar78/prisonescape/items/MetalSpoonItem.java
  src/main/java/net/tiagofar78/prisonescape/items/PlasticShovelItem.java
  src/main/java/net/tiagofar78/prisonescape/items/PlasticSpoonItem.java
  src/main/java/net/tiagofar78/prisonescape/items/WrenchItem.java
Labels: bug fix

#152 Outside Wall Escape
  src/main/java/net/tiagofar78/prisonescape/Events.java
  src/main/java/net/tiagofar78/prisonescape/bukkit/BukkitWorldEditor.java
  src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/PrisonBuilding.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/Wall.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/WallCrack.java
  src/main/java/net/tiagofar78/prisonescape/items/BombItem.java
  src/main/java/net/tiagofar78/prisonescape/items/ItemFactory.java
  src/main/java/net/tiagofar78/prisonescape/managers/ConfigManager.java
  src/main/java/net/tiagofar78/prisonescape/managers/MessageLanguageManager.java
  src/main/resources/config.yml
  src/main/resources/languages/english.yml
Labels: enhancement

#161 Implement hasIllegalItems and hasMetalItems
  src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapePlayer.java
Labels: enhancement

#165 Tool items durability
  src/main/java/net/tiagofar78/prisonescape/Events.java
  src/main/java/net/tiagofar78/prisonescape/bukkit/BukkitMenu.java
  src/main/java/net/tiagofar78/prisonescape/dataobjects/ItemProbability.java
  src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java
  src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapePlayer.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/Chest.java
  src/main/java/net/tiagofar78/prisonescape/items/ItemFactory.java
  src/main/java/net/tiagofar78/prisonescape/items/ToolItem.java
  src/main/java/net/tiagofar78/prisonescape/managers/ConfigManager.java
Labels: enhancement, bug fix

#169 Fix police can drop essential items
  src/main/java/net/tiagofar78/prisonescape/Events.java
  src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java
  src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapePlayer.java
  src/main/java/net/tiagofar78/prisonescape/managers/MessageLanguageManager.java
  src/main/resources/languages/english.yml
Labels: bug fix
