Repository TiagoFar78/PrisonEscape, pull requests merged in 2024-06, with the labels that each got.

#236 Fix energy drink time
  TestServer/plugins/TF_PrisonEscape/config.yml
  src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java
  src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapePlayer.java
Labels: bug fix

#239 TrapDoors spawning on upper half of block
  src/main/java/net/tiagofar78/prisonescape/bukkit/BukkitWorldEditor.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/Vent.java
Labels: bug fix

#201 Metal detectors
  TestServer/plugins/TF_PrisonEscape/config.yml
  src/main/java/net/tiagofar78/prisonescape/Events.java
  src/main/java/net/tiagofar78/prisonescape/bukkit/BukkitSoundBoard.java
  src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/PrisonBuilding.java
  src/main/java/net/tiagofar78/prisonescape/managers/ConfigManager.java
  src/main/resources/config.yml
Labels: enhancement

#238 NPC with camera skin
  TestServer/plugins/TF_PrisonEscape/config.yml
  pom.xml
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/Camera.java
  src/main/java/net/tiagofar78/prisonescape/managers/ConfigManager.java
  src/main/resources/config.yml
  src/main/resources/plugin.yml
Labels: enhancement

#237 Sound Detector Animation
  src/main/java/net/tiagofar78/prisonescape/game/Guard.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/SoundDetector.java
Labels: enhancement

#243 World to Test Server
  TestServer/PrisonEscapeWorld.zip
  TestServer/README.md
Labels: documentation, test server

#253 Bug fixing session
  TestServer/plugins/TF_PrisonEscape/config.yml
  TestServer/plugins/TF_PrisonEscape/languages/english.yml
  src/main/java/net/tiagofar78/prisonescape/Events.java
  src/main/java/net/tiagofar78/prisonescape/bukkit/BukkitTeleporter.java
  src/main/java/net/tiagofar78/prisonescape/game/PEGame.java
  src/main/java/net/tiagofar78/prisonescape/game/PEPlayer.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/Chest.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/Vault.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/doors/CodeDoor.java
  src/main/java/net/tiagofar78/prisonescape/items/DoorCodeItem.java
  src/main/java/net/tiagofar78/prisonescape/items/ItemFactory.java
  src/main/java/net/tiagofar78/prisonescape/managers/MessageLanguageManager.java
  src/main/java/net/tiagofar78/prisonescape/menus/Clickable.java
  src/main/java/net/tiagofar78/prisonescape/menus/CraftingMenu.java
  src/main/java/net/tiagofar78/prisonescape/menus/Shop.java
  src/main/java/net/tiagofar78/prisonescape/menus/TradeMenu.java
  src/main/resources/languages/english.yml
Labels: bug fix

#255 Trap item
  TestServer/plugins/TF_PrisonEscape/config.yml
  TestServer/plugins/TF_PrisonEscape/languages/english.yml
  src/main/java/net/tiagofar78/prisonescape/Events.java
  src/main/java/net/tiagofar78/prisonescape/game/PEGame.java
  src/main/java/net/tiagofar78/prisonescape/game/PEPlayer.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/PrisonBuilding.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/placeables/Camera.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/placeables/SoundDetector.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/placeables/Trap.java
  src/main/java/net/tiagofar78/prisonescape/items/OpenCamerasItem.java
  src/main/java/net/tiagofar78/prisonescape/items/TrapItem.java
  src/main/java/net/tiagofar78/prisonescape/managers/ConfigManager.java
  src/main/java/net/tiagofar78/prisonescape/managers/MessageLanguageManager.java
  src/main/resources/config.yml
  src/main/resources/languages/english.yml
Labels: enhancement

#264 Colored armor to kits
  TestServer/plugins/TF_PrisonEscape/languages/english.yml
  TestServer/server.properties
  src/main/java/net/tiagofar78/prisonescape/kits/Kit.java
  src/main/java/net/tiagofar78/prisonescape/kits/PoliceKit.java
  src/main/java/net/tiagofar78/prisonescape/kits/PrisonerKit.java
  src/main/java/net/tiagofar78/prisonescape/managers/MessageLanguageManager.java
  src/main/resources/languages/english.yml
Labels: enhancement

#265 Fix bars not connecting
  src/main/java/net/tiagofar78/prisonescape/bukkit/BukkitWorldEditor.java
Labels: bug fix

#283 Fixed bug where players in cameras could use gm 3
  TestServer/plugins/TF_PrisonEscape/languages/english.yml
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/placeables/Camera.java
  src/main/java/net/tiagofar78/prisonescape/items/OpenCamerasItem.java
  src/main/java/net/tiagofar78/prisonescape/managers/MessageLanguageManager.java
  src/main/resources/languages/english.yml
Labels: bug fix

#285 Cooldown to events
  src/main/java/net/tiagofar78/prisonescape/Events.java
  src/main/java/net/tiagofar78/prisonescape/PrisonEscape.java
  src/main/java/net/tiagofar78/prisonescape/game/PEGame.java
  src/main/java/net/tiagofar78/prisonescape/game/PEPlayer.java
  src/main/java/net/tiagofar78/prisonescape/listener/PlayerListener.java
  src/main/java/net/tiagofar78/prisonescape/listener/WorldListener.java
Labels: enhancement, bug fix
