Repository TiagoFar78/PrisonEscape, pull requests merged in 2024-05, with the labels that each got.

#157 Implement doors
  .gitignore
  src/main/java/net/tiagofar78/prisonescape/bukkit/BukkitWorldEditor.java
  src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/PrisonBuilding.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/doors/ClickDoorReturnAction.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/doors/CodeDoor.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/doors/Door.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/doors/GoldenDoor.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/doors/GrayDoor.java
  src/main/java/net/tiagofar78/prisonescape/items/DoorCodeItem.java
  src/main/java/net/tiagofar78/prisonescape/items/GoldenKeyItem.java
  src/main/java/net/tiagofar78/prisonescape/items/GrayKeyItem.java
  src/main/java/net/tiagofar78/prisonescape/items/ItemFactory.java
  src/main/java/net/tiagofar78/prisonescape/managers/ConfigManager.java
  src/main/resources/config.yml
  src/main/resources/languages/english.yml
Labels: enhancement

#177 Test server
  .gitignore
  TestServer/README.md
  TestServer/plugins/TF_PrisonEscape/config.yml
  TestServer/plugins/TF_PrisonEscape/languages/english.yml
  TestServer/run.bat
  TestServer/server.properties
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/PrisonBuilding.java
Labels: enhancement

#186 Item not detecting interactions
  src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java
  src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapePlayer.java
  src/main/java/net/tiagofar78/prisonescape/kits/Kit.java
  src/main/java/net/tiagofar78/prisonescape/kits/PoliceKit.java
  src/main/java/net/tiagofar78/prisonescape/kits/PrisionerKit.java
  src/main/java/net/tiagofar78/prisonescape/kits/TeamSelectorKit.java
Labels: bug fix

#191 Fix players not teleporting at beginning of game
  src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java
Labels: bug fix

#188 Helicopter Escape
  TestServer/plugins/TF_PrisonEscape/config.yml
  TestServer/plugins/TF_PrisonEscape/helicopter.schem
  TestServer/plugins/TF_PrisonEscape/languages/english.yml
  TestServer/server.properties
  pom.xml
  src/main/java/net/tiagofar78/prisonescape/bukkit/BukkitWorldEditor.java
  src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/Helicopter.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/PrisonBuilding.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/regions/Region.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/regions/SquaredRegion.java
  src/main/java/net/tiagofar78/prisonescape/items/CellPhoneItem.java
  src/main/java/net/tiagofar78/prisonescape/items/ItemFactory.java
  src/main/java/net/tiagofar78/prisonescape/managers/ConfigManager.java
  src/main/java/net/tiagofar78/prisonescape/managers/MessageLanguageManager.java
  src/main/resources/config.yml
  src/main/resources/languages/english.yml
  src/main/resources/plugin.yml
Labels: enhancement

#193 Fix part of ugly formatter settings
  formatter-config.xml
  src/main/java/net/tiagofar78/prisonescape/bukkit/BukkitMenu.java
  src/main/java/net/tiagofar78/prisonescape/items/ItemFactory.java
Labels: documentation, bug fix

#206 Chests contents
  TestServer/plugins/TF_PrisonEscape/config.yml
Labels: test server

#205 Shop variables
  TestServer/plugins/TF_PrisonEscape/config.yml
  src/main/java/net/tiagofar78/prisonescape/bukkit/BukkitWorldEditor.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/PrisonBuilding.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/Vault.java
  src/main/java/net/tiagofar78/prisonescape/managers/ConfigManager.java
  src/main/resources/config.yml
Labels: bug fix

#204 Rotate vaults
  TestServer/plugins/TF_PrisonEscape/config.yml
  src/main/java/net/tiagofar78/prisonescape/bukkit/BukkitWorldEditor.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/PrisonBuilding.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/Vault.java
  src/main/java/net/tiagofar78/prisonescape/managers/ConfigManager.java
  src/main/resources/config.yml
Labels: bug fix

#203 Player scoreboard
  TestServer/plugins/TF_PrisonEscape/config.yml
  TestServer/plugins/TF_PrisonEscape/languages/english.yml
  src/main/java/net/tiagofar78/prisonescape/game/Guard.java
  src/main/java/net/tiagofar78/prisonescape/game/Prisioner.java
  src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java
  src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapePlayer.java
  src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeTeam.java
  src/main/java/net/tiagofar78/prisonescape/game/ScoreboardData.java
  src/main/java/net/tiagofar78/prisonescape/game/WaitingPlayer.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/Helicopter.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/PrisonBuilding.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/Vault.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/doors/CodeDoor.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/doors/GoldenDoor.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/doors/GrayDoor.java
  src/main/java/net/tiagofar78/prisonescape/managers/MessageLanguageManager.java
  src/main/java/net/tiagofar78/prisonescape/menus/Shop.java
  src/main/resources/languages/english.yml
Labels: enhancement

#207 Cameras
  TestServer/plugins/TF_PrisonEscape/languages/english.yml
  src/main/java/net/tiagofar78/prisonescape/Events.java
  src/main/java/net/tiagofar78/prisonescape/game/Guard.java
  src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java
  src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapePlayer.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/Camera.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/PrisonBuilding.java
  src/main/java/net/tiagofar78/prisonescape/items/CameraItem.java
  src/main/java/net/tiagofar78/prisonescape/items/OpenCamerasItem.java
  src/main/java/net/tiagofar78/prisonescape/kits/Kit.java
  src/main/java/net/tiagofar78/prisonescape/kits/PoliceKit.java
  src/main/java/net/tiagofar78/prisonescape/managers/MessageLanguageManager.java
  src/main/resources/languages/english.yml
Labels: enhancement

#210 Sound Detector
  TestServer/plugins/TF_PrisonEscape/config.yml
  TestServer/plugins/TF_PrisonEscape/languages/english.yml
  src/main/java/net/tiagofar78/prisonescape/bukkit/BukkitMenu.java
  src/main/java/net/tiagofar78/prisonescape/game/Guard.java
  src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java
  src/main/java/net/tiagofar78/prisonescape/game/ScoreboardData.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/PrisonBuilding.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/SoundDetector.java
  src/main/java/net/tiagofar78/prisonescape/items/ItemFactory.java
  src/main/java/net/tiagofar78/prisonescape/items/SensorItem.java
  src/main/java/net/tiagofar78/prisonescape/items/SoundDetectorItem.java
  src/main/java/net/tiagofar78/prisonescape/managers/ConfigManager.java
  src/main/java/net/tiagofar78/prisonescape/managers/MessageLanguageManager.java
  src/main/java/net/tiagofar78/prisonescape/menus/Shop.java
  src/main/resources/config.yml
  src/main/resources/languages/english.yml
Labels: enhancement

#213 Radar Item
  TestServer/plugins/TF_PrisonEscape/config.yml
  src/main/java/net/tiagofar78/prisonescape/bukkit/BukkitEffectGiver.java
  src/main/java/net/tiagofar78/prisonescape/game/Guard.java
  src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java
  src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapePlayer.java
  src/main/java/net/tiagofar78/prisonescape/game/ScoreboardData.java
  src/main/java/net/tiagofar78/prisonescape/items/RadarItem.java
  src/main/java/net/tiagofar78/prisonescape/managers/ConfigManager.java
  src/main/resources/config.yml
Labels: enhancement

#214 Boss Bar Clock
  TestServer/plugins/TF_PrisonEscape/languages/english.yml
  src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java
  src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapePlayer.java
  src/main/java/net/tiagofar78/prisonescape/managers/MessageLanguageManager.java
  src/main/resources/languages/english.yml
Labels: enhancement

#215 Secret Passages
  TestServer/plugins/TF_PrisonEscape/config.yml
  src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java
  src/main/resources/config.yml
Labels: enhancement, test server

#217 Trade Menu
  .gitignore
  TestServer/plugins/TF_PrisonEscape/config.yml
  TestServer/plugins/TF_PrisonEscape/languages/english.yml
  TestServer/server.properties
  src/main/java/net/tiagofar78/prisonescape/Events.java
  src/main/java/net/tiagofar78/prisonescape/bukkit/BukkitMenu.java
  src/main/java/net/tiagofar78/prisonescape/game/Prisioner.java
  src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java
  src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapePlayer.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/Chest.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/Vault.java
  src/main/java/net/tiagofar78/prisonescape/managers/ConfigManager.java
  src/main/java/net/tiagofar78/prisonescape/managers/MessageLanguageManager.java
  src/main/java/net/tiagofar78/prisonescape/menus/Clickable.java
  src/main/java/net/tiagofar78/prisonescape/menus/Shop.java
  src/main/java/net/tiagofar78/prisonescape/menus/TradeMenu.java
  src/main/resources/config.yml
  src/main/resources/languages/english.yml
Labels: enhancement, bug fix

#219 Sound detector particles
  TestServer/plugins/TF_PrisonEscape/config.yml
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/SoundDetector.java
Labels: enhancement

#222 Fixed bug where starting balance was being shown as 0 on scoreboard
  src/main/java/net/tiagofar78/prisonescape/game/Guard.java
Labels: bug fix

#223 Cell Doors
  TestServer/plugins/TF_PrisonEscape/config.yml
  src/main/java/net/tiagofar78/prisonescape/bukkit/BukkitWorldEditor.java
  src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/PrisonBuilding.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/doors/CellDoor.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/doors/Door.java
  src/main/java/net/tiagofar78/prisonescape/managers/ConfigManager.java
  src/main/resources/config.yml
Labels: enhancement

#225 Add Test server instructions
  README.md
  TestServer/README.md
Labels: documentation

#227 Fixed bug where phisical interactions were triggering items
  src/main/java/net/tiagofar78/prisonescape/Events.java
Labels: bug fix

#229 Teleport after escaping
  TestServer/plugins/TF_PrisonEscape/config.yml
  src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/PrisonBuilding.java
  src/main/java/net/tiagofar78/prisonescape/managers/ConfigManager.java
  src/main/resources/config.yml
Labels: enhancement
