Repository TiagoFar78/PrisonEscape, pull requests merged in 2024-03, with the labels that each got.

#29 Implemented start game command
  src/main/java/net/tiagofar78/prisonescape/PrisonEscape.java
  src/main/java/net/tiagofar78/prisonescape/commands/PrisonEscapeCommand.java
  src/main/java/net/tiagofar78/prisonescape/commands/PrisonEscapeSubcommandExecutor.java
  src/main/java/net/tiagofar78/prisonescape/commands/StartSubcommand.java
  src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java
  src/main/java/net/tiagofar78/prisonescape/managers/ConfigManager.java
  src/main/java/net/tiagofar78/prisonescape/managers/GameManager.java
  src/main/java/net/tiagofar78/prisonescape/managers/MessageLanguageManager.java
Labels: enhancement

#30 Implemented force start command
  src/main/java/net/tiagofar78/prisonescape/commands/ForceStartSucommand.java
  src/main/java/net/tiagofar78/prisonescape/commands/PrisonEscapeCommand.java
  src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java
  src/main/java/net/tiagofar78/prisonescape/managers/MessageLanguageManager.java
Labels: enhancement

#31 Implement join command
  src/main/java/net/tiagofar78/prisonescape/commands/ForceStartSubcommand.java
  src/main/java/net/tiagofar78/prisonescape/commands/JoinSubcommand.java
  src/main/java/net/tiagofar78/prisonescape/commands/PrisonEscapeCommand.java
  src/main/java/net/tiagofar78/prisonescape/managers/MessageLanguageManager.java
Labels: enhancement

#45 Implement waiting phase
  src/main/java/net/tiagofar78/prisonescape/bukkit/BukkitMessageSender.java
  src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java
  src/main/java/net/tiagofar78/prisonescape/managers/ConfigManager.java
  src/main/java/net/tiagofar78/prisonescape/managers/MessageLanguageManager.java
Labels: enhancement

#53 Completed ConfigManager and MessagesLanguageManager
  config.yml
  src/main/java/net/tiagofar78/prisonescape/PrisonEscape.java
  src/main/java/net/tiagofar78/prisonescape/PrisonEscapeResources.java
  src/main/java/net/tiagofar78/prisonescape/commands/PrisonEscapeCommand.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/Chest.java
  src/main/java/net/tiagofar78/prisonescape/managers/ConfigManager.java
  src/main/java/net/tiagofar78/prisonescape/managers/MessageLanguageManager.java
  src/main/resources/config.yml
  src/main/resources/languages/english.yml
Labels: enhancement

#56 Implemented finished phase
  src/main/java/net/tiagofar78/prisonescape/bukkit/BukkitMessageSender.java
  src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java
  src/main/java/net/tiagofar78/prisonescape/managers/ConfigManager.java
  src/main/java/net/tiagofar78/prisonescape/managers/MessageLanguageManager.java
  src/main/resources/config.yml
  src/main/resources/languages/english.yml
Labels: enhancement

#64 Added plugin.yml file and fixed small warnings.
  pom.xml
  src/main/java/net/tiagofar78/prisonescape/PrisonEscape.java
  src/main/java/net/tiagofar78/prisonescape/PrisonEscapeResources.java
  src/main/java/net/tiagofar78/prisonescape/commands/ForceStopSubcommand.java
  src/main/java/net/tiagofar78/prisonescape/commands/JoinSubcommand.java
  src/main/java/net/tiagofar78/prisonescape/commands/LeaveSubcommand.java
  src/main/java/net/tiagofar78/prisonescape/commands/RejoinSubcommand.java
  src/main/java/net/tiagofar78/prisonescape/commands/StartSubcommand.java
  src/main/java/net/tiagofar78/prisonescape/commands/StopSubcommand.java
  src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapePlayer.java
  src/main/java/net/tiagofar78/prisonescape/managers/MessageLanguageManager.java
  src/main/resources/config.yml
  src/main/resources/languages/english.yml
  src/main/resources/plugin.yml
Labels: enhancement, bug fix

#70 Implemented team selector kit
  src/main/java/net/tiagofar78/prisonescape/PrisonEscape.java
  src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java
  src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeItem.java
  src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapePlayer.java
  src/main/java/net/tiagofar78/prisonescape/kits/TeamSelectorKit.java
  src/main/java/net/tiagofar78/prisonescape/managers/MessageLanguageManager.java
  src/main/resources/languages/english.yml
Labels: enhancement

#76 Fix: out of building escape not working
  src/main/java/net/tiagofar78/prisonescape/Events.java
  src/main/java/net/tiagofar78/prisonescape/PrisonEscape.java
  src/main/java/net/tiagofar78/prisonescape/commands/ForceStartSubcommand.java
  src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java
  src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapePlayer.java
  src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeTeam.java
  src/main/java/net/tiagofar78/prisonescape/game/Settings.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/PrisonBuilding.java
  src/main/java/net/tiagofar78/prisonescape/managers/ConfigManager.java
  src/main/java/net/tiagofar78/prisonescape/managers/MessageLanguageManager.java
  src/main/resources/config.yml
  src/main/resources/languages/english.yml
Labels: bug fix

#78 Small bugs fixed
  src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java
  src/main/java/net/tiagofar78/prisonescape/game/phases/Finished.java
  src/main/java/net/tiagofar78/prisonescape/game/phases/Ongoing.java
  src/main/java/net/tiagofar78/prisonescape/game/phases/Waiting.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/PrisonBuilding.java
  src/main/java/net/tiagofar78/prisonescape/managers/MessageLanguageManager.java
  src/main/resources/languages/english.yml
Labels: bug fix

#80 Vault inteligence
  src/main/java/net/tiagofar78/prisonescape/Events.java
  src/main/java/net/tiagofar78/prisonescape/bukkit/BukkitItems.java
  src/main/java/net/tiagofar78/prisonescape/bukkit/BukkitMenu.java
  src/main/java/net/tiagofar78/prisonescape/bukkit/BukkitWorldEditor.java
  src/main/java/net/tiagofar78/prisonescape/game/MenuType.java
  src/main/java/net/tiagofar78/prisonescape/game/PrisonEscapeGame.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/PrisonBuilding.java
  src/main/java/net/tiagofar78/prisonescape/game/prisonbuilding/Vault.java
  src/main/java/net/tiagofar78/prisonescape/managers/ConfigManager.java
  src/main/java/net/tiagofar78/prisonescape/managers/MessageLanguageManager.java
  src/main/resources/config.yml
  src/main/resources/languages/english.yml
Labels: enhancement
